/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sweetz_camerapreview_NativeFilter */

#ifndef _Included_com_sweetz_camerapreview_NativeFilter
#define _Included_com_sweetz_camerapreview_NativeFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sweetz_camerapreview_NativeFilter
 * Method:    decodeYUV420SP
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_com_sweetz_camerapreview_NativeFilter_decodeYUV420SP
  (JNIEnv *, jclass, jintArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
